import { create } from "zustand";
import { persist } from "zustand/middleware";

export type Language = "en" | "es";

type Dictionary = Record<string, string>;

const DICTIONARY: Record<Language, Dictionary> = {
  en: {
    dashboard: "Dashboard",
    projects: "Projects",
    new_project: "New Project",
    new_room: "New Room",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete this?",
    cancel: "Cancel",
    save: "Save",
    back: "Back",
    next: "Next",
    create: "Create",
    rooms: "Rooms",
    layouts: "Layouts",
    settings: "Settings",
    style: "Style",
    room_type: "Room Type",
    width: "Width",
    length: "Length",
    height: "Height",
    generate_layout: "Generate Layout",
    no_projects: "No projects found. Create your first one!",
    project_name: "Project Name",
    room_name: "Room Name",
    select_all: "Select all",
    primary: "Primary",
    set_primary: "Set primary",
    compare: "Compare",
    my_bedroom: "My bedroom",
    scandinavian: "Scandinavian",
    minimal: "Minimal",
    industrial: "Industrial",
    japandi: "Japandi",
    mid_century: "Mid-Century",
    // Landing Page
    hero_title: "Design any room",
    hero_subtitle: "in 30 seconds",
    hero_desc: "Interior Flow 3D turns dimensions and a style into a 3D layout you can rotate, inspect, and save. No designer needed.",
    hero_cta: "Try it free, no signup",
    footer_tagline: "Interior Flow 3D — Your AI interior design copilot. Free during beta.",
    how_it_works: "How it works",
    step1_title: "1. Set your room",
    step1_body: "Enter dimensions for any room — living, bedroom, dining, or home office.",
    step2_title: "2. Pick a style",
    step2_body: "Scandinavian, Minimal, Industrial, Japandi, or Mid-century — five curated palettes.",
    step3_title: "3. Get a 3D layout",
    step3_body: "AI places furniture, picks a palette, and explains every decision in under 10 seconds.",
    whats_included: "What's included",
    pricing: "Pricing",
    free_beta: "Free during beta",
    pro_coming_soon: "Pro coming soon — unlock premium catalog items, unlimited generations, and priority support.",
    free_gen_limit: "10 free generations per day",
    room_types_feat: "4 room types",
    room_types_desc: "Living room, bedroom, dining room, and home office — each with tailored furniture and slots.",
    styles_feat: "5 styles",
    styles_desc: "Scandinavian, Minimal, Industrial, Japandi, and Mid-century — each with a curated palette.",
    catalog_feat: "~40 catalog items",
    catalog_desc: "Tagged furniture with smart placement, zone-aware AI, and first-person design rationale.",
    // Dashboard & Inspector
    new_project_btn: "New Project",
    no_projects_yet: "You don't have any projects yet.",
    create_first_project: "Create your first project to start designing.",
    project_deleted: "Project deleted successfully",
    room_deleted: "Room deleted successfully",
    layout_deleted: "Layout deleted successfully",
    design_rationale: "Design Rationale",
    furniture_list: "Furniture List",
    style_and_palette: "Style & Palette",
    regenerate: "Regenerate",
    adjust: "Adjust",
    save_design: "Save Design",
    saving: "Saving...",
    saved: "Saved!",
    dimensions: "Dimensions",
    facing: "Facing",
    slot: "Slot",
    zone: "Zone",
    try_no_signup: "Try without signing in",
    sign_in: "Sign in",
    quick_generate: "Quick generate",
    delete_selected: "Delete Selected",
    quick_generations: "Quick Generations",
    deselect_all: "Deselect all",
    delete_multiple_title: "Delete Multiple Projects",
    delete_multiple_desc: "Are you sure you want to delete these projects? This action cannot be undone.",
    auth_subtitle: "Generate a 3D interior layout in seconds. Sign in to save your work.",
    layout_title: "Layout",
    warnings: "Warnings",
    adjust_prefs: "Adjust preferences",
    share_link: "Share link",
    more_seating: "More seating",
    more_open_space: "More open space",
    more_storage: "More storage",
    show_walls: "Show walls",
    hide_walls: "Hide walls",
    replace_item: "Replace this item",
    hide_replacements: "Hide replacements",
    save_to_replace: "Save to replace",
    wall: "Wall",
    floor: "Floor",
    accent: "Accent",
    start_from_photo: "Start from a photo",
    choose_style_desc: "Choose a design style that resonates with you and we'll help you create the perfect layout.",
    explore_aesthetic: "Explore aesthetic",
    overview: "Overview",
    getting_started: "Getting Started",
    getting_started_desc: "Create a new project or select a style from the gallery to start designing your dream space.",
    pro_tips: "Pro Tips",
    quick_generate_tip: "Quick Generate",
    quick_generate_desc: "Use templates to create a layout in under 30 seconds.",
    save_variants_tip: "Save Variants",
    save_variants_desc: "You can save multiple design variants for the same room.",
    multi_room_tip: "Multi-room Projects",
    multi_room_desc: "Keep your whole house organized by adding multiple rooms to one project.",
    need_help: "Need help? Check our documentation or contact support.",
    scene_details: "Scene Details",
    room_specs: "Room Specs",
    total_area: "Total Area",
    inspector_tip: "Use the Inspector to verify room constraints before generating new layouts.",
    current_config: "Current Config",
    wizard_tip: "Your design is being updated in real-time as you progress through the wizard.",
    type: "Type",
    size: "Size",
    use_template: "Use this template",
    start_from_template: "Start from a template",
    living_room: "Living Room",
    bedroom: "Bedroom",
    dining_room: "Dining Room",
    home_office: "Home Office",
    none: "None",
    no_rooms_yet: "No rooms yet",
    add_room_desc: "Add your first room to start designing layouts.",
    add_a_room: "Add a room",
    delete_multiple_rooms_title: "Delete Multiple Rooms",
    delete_multiple_rooms_desc: "Are you sure you want to delete these rooms? This action will permanently remove all layouts within these rooms.",
    click_to_rename: "Click to rename",
    no_layouts_yet: "No layouts yet",
    add_layout_desc: "Generate your first 3D layout using our AI-powered wizard.",
    add_a_layout: "Add a layout",
    delete_multiple_layouts_title: "Delete Multiple Layouts",
    delete_multiple_layouts_desc: "Are you sure you want to delete these layouts? This action cannot be undone.",
    new_layout: "New Layout",
    enter_layout_name: "Enter a name for this layout",
    delete_room: "Delete Room",
    delete_room_desc: "Are you sure you want to delete \"${name}\"? This will permanently remove all layouts within this room.",
    delete_layout: "Delete Layout",
    delete_layout_desc: "Are you sure you want to delete \"${name}\"? This action cannot be undone.",
    width_m: "Width (m)",
    length_m: "Length (m)",
    height_m: "Height (m)",
    creating: "Creating...",
    delete_project: "Delete Project",
    delete_project_desc: "Are you sure you want to delete \"${name}\"? This will permanently remove all rooms and layouts within this project.",
    // Wizard
    room_type_title: "Room Type",
    room_type_subtitle: "What kind of room are you designing?",
    room_dimensions: "Room dimensions",
    dimensions_desc: "Enter approximate measurements in metres.",
    choose_style: "Choose a style",
    choose_style_subtitle: "The AI will honour this aesthetic throughout.",
    any_preferences: "Any preferences?",
    preferences_desc: "Pick up to 2. Skip to let the AI decide.",
    generate: "Generate",
    generating: "Generating...",
    designing_room: "Designing your room...",
    style_tagline_scandinavian: "Light woods, soft textiles, cozy warmth",
    style_tagline_minimal: "Calm surfaces, intentional negative space",
    style_tagline_japandi: "Japanese minimalism meets Scandi comfort",
    style_tagline_mid_century: "Retro curves, bold colors, teak accents",
    style_tagline_industrial: "Raw metal, concrete, exposed structure",
    preferences: "Preferences",
    // New stragglers
    sign_in_to_save: "Sign in to save",
    auth_google: "Continue with Google",
    or: "or",
    email: "Email",
    sending_link: "Sending…",
    send_magic_link: "Send magic link",
    check_inbox: "Check your inbox for the sign-in link.",
    magic_link_desc: "We'll send you a magic link or use Google.",
    account: "Account",
    sign_in_menu: "Sign In",
    sign_out: "Sign out",
    settings_soon: "Settings (Coming soon)",
    free_plan: "Free plan",
    free_var: "free var",
    free_vars: "free vars",
    preview_3d: "3D preview",
    confirm: "Confirm",
    deleting: "Deleting...",
    close: "Close",
    toggle_theme: "Toggle theme",
    project_not_found: "Project not found.",
    room_not_found: "Room not found.",
    layout_not_found: "Layout not found.",
    something_went_wrong: "Something went wrong",
    hide_layout_info: "Hide Layout Info",
    show_layout_info: "Show Layout Info",
    // Catalog
    sofa_3seat: "3-seat sofa",
    loveseat: "Loveseat",
    sectional_sofa: "Sectional sofa",
    armchair: "Armchair",
    accent_chair: "Accent chair",
    ottoman: "Ottoman",
    coffee_table: "Coffee table",
    side_table: "Side table",
    console_table: "Console table",
    tv_stand: "TV stand",
    media_console: "Media console",
    bookshelf: "Bookshelf",
    bookshelf_tall: "Tall bookshelf",
    corner_shelf: "Corner shelf",
    floor_lamp: "Floor lamp",
    wall_sconce_pair: "Wall sconce pair",
    rug: "Area rug",
    round_rug: "Round rug",
    plant_large: "Large plant",
    small_plant: "Small plant",
    floor_mirror: "Floor mirror",
    wall_art_set: "Wall art set",
    bar_cart: "Bar cart",
    magazine_rack: "Magazine rack",
    bed_queen: "Queen bed",
    bed_king: "King bed",
    bed_single: "Single bed",
    nightstand: "Nightstand",
    bedside_lamp: "Bedside lamp",
    dresser: "Dresser",
    wardrobe: "Wardrobe",
    desk: "Desk",
    office_chair: "Office chair",
    dining_table: "Dining table",
    dining_chair: "Dining chair",
    sideboard: "Sideboard",
    // Materials
    exposed_brick: "Exposed Brick",
    warm_wood: "Warm Wood",
    matte_black: "Matte Black",
    light_oak: "Light Oak",
    cool_concrete: "Cool Concrete",
    sage_green: "Sage Green",
    navy_blue: "Navy Blue",
    terracotta: "Terracotta",
    cream_boucle: "Cream Boucle",
    walnut: "Walnut",
    brass: "Brass",
    polished_chrome: "Polished Chrome",
    off_white: "Off White",
    charcoal: "Charcoal",
    // Slot Labels
    north_wall_left: "Back wall — left side",
    north_wall_center: "Back wall — centered",
    north_wall_right: "Back wall — right side",
    east_wall_left: "Right wall — far end",
    east_wall_center: "Right wall — centered",
    east_wall_right: "Right wall — near end",
    south_wall_left: "Front wall — left side",
    south_wall_center: "Front wall — centered",
    south_wall_right: "Front wall — right side",
    west_wall_left: "Left wall — far end",
    west_wall_center: "Left wall — centered",
    west_wall_right: "Left wall — near end",
    corner_NE: "Back-right corner",
    corner_NW: "Back-left corner",
    corner_SE: "Front-right corner",
    corner_SW: "Front-left corner",
    center: "Room center",
    center_front: "Center, toward the front",
    entry: "Near the entryway",
    bed_center: "Bed center",
    table_center: "Table center",
    desk_anchor: "Desk anchor",
    free_designs_project: "Free Designs",
    quick_room: "Quick Room",
  },
  es: {
    dashboard: "Panel de Control",
    projects: "Proyectos",
    new_project: "Nuevo Proyecto",
    new_room: "Nueva Habitación",
    delete: "Eliminar",
    confirm_delete: "¿Estás seguro de que quieres eliminar esto?",
    cancel: "Cancelar",
    save: "Guardar",
    back: "Volver",
    next: "Siguiente",
    create: "Crear",
    rooms: "Habitaciones",
    layouts: "Diseños",
    settings: "Ajustes",
    style: "Estilo",
    room_type: "Tipo de habitación",
    width: "Ancho",
    length: "Largo",
    height: "Alto",
    generate_layout: "Generar Diseño",
    no_projects: "No se encontraron proyectos. ¡Crea el primero!",
    project_name: "Nombre del Proyecto",
    room_name: "Nombre de la Habitación",
    select_all: "Seleccionar todo",
    primary: "Principal",
    set_primary: "Marcar principal",
    compare: "Comparar",
    my_bedroom: "Mi dormitorio",
    scandinavian: "Escandinavo",
    minimal: "Minimalista",
    industrial: "Industrial",
    japandi: "Japandi",
    mid_century: "Mid-Century",
    // Landing Page
    hero_title: "Diseña cualquier habitación",
    hero_subtitle: "en 30 segundos",
    hero_desc: "Interior Flow 3D convierte dimensiones y un estilo en un diseño 3D que puedes rotar, inspeccionar y guardar. Sin necesidad de ser diseñador.",
    hero_cta: "Pruébalo gratis, sin registro",
    footer_tagline: "Interior Flow 3D — Tu copiloto de diseño de interiores con IA. Gratis durante la beta.",
    how_it_works: "Cómo funciona",
    step1_title: "1. Define tu habitación",
    step1_body: "Introduce las dimensiones de cualquier estancia: salón, dormitorio, comedor o despacho.",
    step2_title: "2. Elige un estilo",
    step2_body: "Escandinavo, Minimalista, Industrial, Japandi o Mid-century — cinco paletas seleccionadas.",
    step3_title: "3. Obtén tu diseño 3D",
    step3_body: "La IA coloca los muebles, elige la paleta y explica cada decisión en menos de 10 segundos.",
    whats_included: "Qué incluye",
    pricing: "Precios",
    free_beta: "Gratis durante la beta",
    pro_coming_soon: "Pro próximamente — desbloquea muebles premium, generaciones ilimitadas y soporte prioritario.",
    free_gen_limit: "10 generaciones gratuitas al día",
    room_types_feat: "4 tipos de habitaciones",
    room_types_desc: "Salón, dormitorio, comedor y despacho — cada uno con muebles y espacios a medida.",
    styles_feat: "5 estilos",
    styles_desc: "Escandinavo, Minimalista, Industrial, Japandi y Mid-century — cada uno con su paleta curada.",
    catalog_feat: "~40 muebles en catálogo",
    catalog_desc: "Muebles etiquetados con colocación inteligente, IA por zonas y explicaciones de diseño.",
    // Dashboard & Inspector
    new_project_btn: "Nuevo Proyecto",
    no_projects_yet: "Aún no tienes ningún proyecto.",
    create_first_project: "Crea tu primer proyecto para empezar a diseñar.",
    project_deleted: "Proyecto eliminado con éxito",
    room_deleted: "Habitación eliminada con éxito",
    layout_deleted: "Diseño eliminado con éxito",
    design_rationale: "Concepto de Diseño",
    furniture_list: "Lista de Muebles",
    style_and_palette: "Estilo y Paleta",
    regenerate: "Regenerar",
    adjust: "Ajustar",
    save_design: "Guardar Diseño",
    saving: "Guardando...",
    saved: "¡Guardado!",
    dimensions: "Dimensiones",
    facing: "Orientación",
    slot: "Espacio",
    zone: "Zona",
    try_no_signup: "Probar sin registrarse",
    sign_in: "Iniciar sesión",
    quick_generate: "Generación rápida",
    delete_selected: "Eliminar seleccionados",
    quick_generations: "Generaciones rápidas",
    deselect_all: "Deseleccionar todo",
    delete_multiple_title: "Eliminar múltiples proyectos",
    delete_multiple_desc: "¿Estás seguro de que quieres eliminar estos proyectos? Esta acción no se puede deshacer.",
    auth_subtitle: "Genera un diseño 3D en segundos. Inicia sesión para guardar tu trabajo.",
    layout_title: "Distribución",
    warnings: "Avisos",
    adjust_prefs: "Ajustar preferencias",
    share_link: "Compartir enlace",
    more_seating: "Más asientos",
    more_open_space: "Más espacio abierto",
    more_storage: "Más almacenaje",
    show_walls: "Mostrar paredes",
    hide_walls: "Ocultar paredes",
    replace_item: "Reemplazar mueble",
    hide_replacements: "Ocultar opciones",
    save_to_replace: "Guardar para reemplazar",
    wall: "Pared",
    floor: "Suelo",
    accent: "Acento",
    start_from_photo: "Empieza desde una foto",
    choose_style_desc: "Elige un estilo de diseño que te inspire y te ayudaremos a crear la distribución perfecta.",
    explore_aesthetic: "Explorar estética",
    overview: "Resumen",
    getting_started: "Empezando",
    getting_started_desc: "Crea un nuevo proyecto o selecciona un estilo de la galería para empezar a diseñar.",
    pro_tips: "Consejos Pro",
    quick_generate_tip: "Generación Rápida",
    quick_generate_desc: "Usa plantillas para crear un diseño en menos de 30 segundos.",
    save_variants_tip: "Guardar Variantes",
    save_variants_desc: "Puedes guardar múltiples variantes de diseño para la misma habitación.",
    multi_room_tip: "Proyectos Multihabitación",
    multi_room_desc: "Mantén toda tu casa organizada añadiendo varias habitaciones a un proyecto.",
    need_help: "¿Necesitas ayuda? Consulta nuestra documentación o contacta con soporte.",
    scene_details: "Detalles de la Escena",
    room_specs: "Especificaciones",
    total_area: "Área Total",
    inspector_tip: "Usa el Inspector para verificar las dimensiones antes de generar nuevos diseños.",
    current_config: "Configuración Actual",
    wizard_tip: "Tu diseño se actualiza en tiempo real mientras avanzas en el asistente.",
    type: "Tipo",
    size: "Tamaño",
    use_template: "Usar esta plantilla",
    start_from_template: "Empezar desde una plantilla",
    living_room: "Salón",
    bedroom: "Dormitorio",
    dining_room: "Comedor",
    home_office: "Despacho",
    none: "Ninguno",
    no_rooms_yet: "Aún no hay habitaciones",
    add_room_desc: "Añade tu primera habitación para empezar a diseñar distribuciones.",
    add_a_room: "Añadir una habitación",
    delete_multiple_rooms_title: "Eliminar varias habitaciones",
    delete_multiple_rooms_desc: "¿Estás seguro de que quieres eliminar estas habitaciones? Esta acción eliminará permanentemente todos los diseños dentro de ellas.",
    click_to_rename: "Haz clic para renombrar",
    no_layouts_yet: "Aún no hay diseños",
    add_layout_desc: "Genera tu primer diseño 3D usando nuestro asistente con IA.",
    add_a_layout: "Añadir un diseño",
    delete_multiple_layouts_title: "Eliminar varios diseños",
    delete_multiple_layouts_desc: "¿Estás seguro de que quieres eliminar estos diseños? Esta acción no se puede deshacer.",
    new_layout: "Nuevo Diseño",
    enter_layout_name: "Introduce un nombre para este diseño",
    delete_room: "Eliminar Habitación",
    delete_room_desc: "¿Estás seguro de que quieres eliminar \"${name}\"? Esta acción eliminará permanentemente todos los diseños dentro de esta habitación.",
    delete_layout: "Eliminar Diseño",
    delete_layout_desc: "¿Estás seguro de que quieres eliminar \"${name}\"? Esta acción no se puede deshacer.",
    width_m: "Ancho (m)",
    length_m: "Largo (m)",
    height_m: "Alto (m)",
    creating: "Creando...",
    delete_project: "Eliminar Proyecto",
    delete_project_desc: "¿Estás seguro de que quieres eliminar \"${name}\"? Esta acción eliminará permanentemente todas las habitaciones y diseños dentro de este proyecto.",
    // Wizard
    room_type_title: "Tipo de habitación",
    room_type_subtitle: "¿Qué tipo de habitación estás diseñando?",
    room_dimensions: "Dimensiones de la habitación",
    dimensions_desc: "Introduce medidas aproximadas en metros.",
    choose_style: "Elige un estilo",
    choose_style_subtitle: "La IA respetará esta estética en todo el diseño.",
    any_preferences: "¿Alguna preferencia?",
    preferences_desc: "Elige hasta 2. Salta este paso para que la IA decida.",
    generate: "Generar",
    generating: "Generando...",
    designing_room: "Diseñando tu habitación...",
    style_tagline_scandinavian: "Maderas claras, textiles suaves, calidez acogedora",
    style_tagline_minimal: "Superficies serenas, espacios intencionados",
    style_tagline_japandi: "Minimalismo japonés y confort nórdico",
    style_tagline_mid_century: "Curvas retro, colores vivos, detalles en teca",
    style_tagline_industrial: "Metal en bruto, hormigón, estructuras a la vista",
    preferences: "Preferencias",
    // New stragglers
    sign_in_to_save: "Inicia sesión para guardar",
    auth_google: "Continuar con Google",
    or: "o",
    email: "Correo electrónico",
    sending_link: "Enviando…",
    send_magic_link: "Enviar enlace mágico",
    check_inbox: "Revisa tu bandeja de entrada para el enlace de acceso.",
    magic_link_desc: "Te enviaremos un enlace mágico o puedes usar Google.",
    account: "Cuenta",
    sign_in_menu: "Iniciar Sesión",
    sign_out: "Cerrar sesión",
    settings_soon: "Ajustes (Próximamente)",
    free_plan: "Plan gratuito",
    free_var: "gen. gratuita",
    free_vars: "gen. gratuitas",
    preview_3d: "Vista previa 3D",
    confirm: "Confirmar",
    deleting: "Eliminando...",
    close: "Cerrar",
    toggle_theme: "Cambiar tema",
    project_not_found: "Proyecto no encontrado.",
    room_not_found: "Habitación no encontrada.",
    layout_not_found: "Diseño no encontrado.",
    something_went_wrong: "Algo ha ido mal",
    hide_layout_info: "Ocultar info",
    show_layout_info: "Mostrar info",
    // Catalog
    sofa_3seat: "Sofá de 3 plazas",
    loveseat: "Sofá biplaza",
    sectional_sofa: "Sofá rinconera",
    armchair: "Sillón",
    accent_chair: "Silla de acento",
    ottoman: "Puf",
    coffee_table: "Mesa de centro",
    side_table: "Mesa auxiliar",
    console_table: "Mesa consola",
    tv_stand: "Mueble TV",
    media_console: "Consola multimedia",
    bookshelf: "Estantería",
    bookshelf_tall: "Estantería alta",
    corner_shelf: "Estantería esquinera",
    floor_lamp: "Lámpara de pie",
    wall_sconce_pair: "Pareja de apliques",
    rug: "Alfombra",
    round_rug: "Alfombra redonda",
    plant_large: "Planta grande",
    small_plant: "Planta pequeña",
    floor_mirror: "Espejo de pie",
    wall_art_set: "Conjunto de cuadros",
    bar_cart: "Carrito bar",
    magazine_rack: "Revistero",
    bed_queen: "Cama Queen",
    bed_king: "Cama King",
    bed_single: "Cama individual",
    nightstand: "Mesita de noche",
    bedside_lamp: "Lámpara de noche",
    dresser: "Cómoda",
    wardrobe: "Armario",
    desk: "Escritorio",
    office_chair: "Silla de oficina",
    dining_table: "Mesa de comedor",
    dining_chair: "Silla de comedor",
    sideboard: "Aparador",
    // Materials
    exposed_brick: "Ladrillo Visto",
    warm_wood: "Madera Cálida",
    matte_black: "Negro Mate",
    light_oak: "Roble Claro",
    cool_concrete: "Hormigón Frío",
    sage_green: "Verde Salvia",
    navy_blue: "Azul Marino",
    terracotta: "Terracota",
    cream_boucle: "Bouclé Crema",
    walnut: "Nogal",
    brass: "Latón",
    polished_chrome: "Cromo Pulido",
    off_white: "Blanco Roto",
    charcoal: "Antracita",
    // Slot Labels
    north_wall_left: "Pared trasera — izquierda",
    north_wall_center: "Pared trasera — centro",
    north_wall_right: "Pared trasera — derecha",
    east_wall_left: "Pared derecha — fondo",
    east_wall_center: "Pared derecha — centro",
    east_wall_right: "Pared derecha — frente",
    south_wall_left: "Pared frontal — izquierda",
    south_wall_center: "Pared frontal — centro",
    south_wall_right: "Pared frontal — derecha",
    west_wall_left: "Pared izquierda — fondo",
    west_wall_center: "Pared izquierda — centro",
    west_wall_right: "Pared izquierda — frente",
    corner_NE: "Esquina trasera-derecha",
    corner_NW: "Esquina trasera-izquierda",
    corner_SE: "Esquina frontal-derecha",
    corner_SW: "Esquina frontal-izquierda",
    center: "Centro de la habitación",
    center_front: "Centro, hacia el frente",
    entry: "Cerca de la entrada",
    bed_center: "Centro de la cama",
    table_center: "Centro de la mesa",
    desk_anchor: "Ancla del escritorio",
    free_designs_project: "Diseños libres",
    quick_room: "Habitación rápida",
  },
};

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: "en",
      setLanguage: (language) => set({ language }),
      t: (key) => {
        const { language } = get();
        // Handle underscore/space inconsistency
        const normalizedKey = key.replace(/ /g, "_").toLowerCase();
        return DICTIONARY[language][normalizedKey] || DICTIONARY[language][key] || key;
      },
    }),
    {
      name: "language-storage",
    },
  ),
);
